[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
kosame = { workspace = true, features = ["serde"] }
postgres = "0.19.10"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
