name: kosame
services:
  postgres:
    image: postgres:18rc1-alpine3.22
    shm_size: 128mb
    command: postgres -c shared_preload_libraries="pg_stat_statements, auto_explain" -c pg_stat_statements.track=all -c max_connections=256
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
