[package]
name = "example_postgres"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
kosame = { workspace = true, features = ["serde", "postgres"] }
postgres = "0.19.12"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
