[package]
name = "kosame"
version = "0.1.0"
edition = "2024"

[features]
default = ["postgres"]

mssql = []
mysql = []
postgres = ["dep:postgres-protocol", "dep:postgres-types", "dep:tokio-postgres"]
sqlite = []

serde = ["serde-serialize", "serde-deserialize", "kosame_macro/serde"]
serde-serialize = ["dep:serde", "kosame_macro/serde-serialize"]
serde-deserialize = ["dep:serde", "kosame_macro/serde-deserialize"]

[dependencies]
fallible-iterator = "0.2.0"
futures-core = "0.3.31"
kosame_macro.workspace = true
postgres-protocol = { version = "0.6.8", optional = true }
postgres-types = { version = "0.2.9", optional = true }
serde = { version = "1.0.226", optional = true }
tokio-postgres = { version = "0.7.14", optional = true }
