[package]
name = "kosame"
version = "0.1.0"
edition = "2024"

[dependencies]
const_format = "0.2.34"
fallible-iterator = "0.2.0"
kosame_macro.workspace = true
postgres-protocol = "0.6.8"
postgres-types = "0.2.9"
